unique_name: productsubcategories
object_type: dataset
label: productsubcategories
columns:
  - name: productsubcategoryid
    data_type: int
  - name: productcategoryid
    data_type: int
  - name: productsubcategoryname
    data_type: string
connection_id: con_postgres_training
table: productsubcategories
